# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.0'
use_modular_headers!   # Enable modular headers globally

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

source 'https://github.com/CocoaPods/Specs.git'

target 'schoolapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'SDWebImage', :modular_headers => true
  pod 'SDWebImageSVGCoder', :modular_headers => true

  # Fix react-native-bottom-tabs issue
  pod 'react-native-bottom-tabs', :path => '../node_modules/react-native-bottom-tabs'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
